version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  be:
    build: .
    ports:
      - 80:3000
    depends_on:
      - db
    restart: unless-stopped
volumes:
  db:
    driver: local
